import assert from 'node:assert/strict';
import Land from '../demos/voxels/landscape.bend';
import W from '../engine/voxel/world.bend';
import Input from '../demos/camera_lab/input.bend';
import App from '../demos/camera_lab/app.bend';
const p=(x,y,z)=>({$:'Point',x,y,z});
const list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'});
const length=xs=>{let n=0;while(xs.$.endsWith('Con')){n++;xs=xs.tail;}return n;};
const chunks=cache=>{const out={};while(cache.$.endsWith('Chunk')){out[cache.id]=cache.faces;cache=cache.next;}return out;};
let state={$:'Landscape',world:W.create(32,16,32).value,cache:Land.chunks(16n),dirty:0,rebuilt:0};
state=Land.edit(state,p(7,3,4),1);state=Land.edit(state,p(8,3,4),1);
assert.equal(state.dirty,3,'chunk boundary invalidates both neighbors');
state=Land.clean(state);assert.equal(state.rebuilt,2);
let cache=chunks(state.cache);assert.equal(length(cache[0]),10);assert.equal(length(cache[1]),10);
state=Land.edit(state,p(7,3,4),0);state=Land.clean(state);assert.equal(state.rebuilt,2);
cache=chunks(state.cache);assert.equal(length(cache[0]),0);assert.equal(length(cache[1]),12,'neighbor exposes removed boundary face');
const retained=cache[1];state=Land.clean(state);assert.equal(state.rebuilt,0);assert.equal(chunks(state.cache)[1],retained,'unchanged chunk retains its mesh');
const world=structuredClone(state.world.cells);state=Land.edit(state,p(-1,3,4),1);assert.deepEqual(state.world.cells,world);
let c=Input.initial(true);const saved=structuredClone(c);
c=Input.key(32,true,c);c=Input.key(108,true,c);c=Input.advance(c,.1);
assert.equal(c.time,0,'camera can move while animation is paused');assert.notEqual(c.rig.orbit.yaw,saved.rig.orbit.yaw);
c=Input.key(113,true,c);assert.equal(c.quality,2);assert.equal(c.paused,true);
c=Input.key(111,true,c);assert.equal(c.rig.orthographic,true);
const before=Input.camera(c.rig);c=Input.key(102,true,c);const after=Input.camera(c.rig);
for(const k of ['x','y','z']) assert.ok(Math.abs(before.eye[k]-after.eye[k])<.0001,'switching controls preserves camera pose');
// A click's own coordinates are used before later movement in the same batch.
const setup=Input.initial(true),a=App.create(true),b=App.create(true);
const clicked=App.events(list([{$:'Mouse',x:320,y:320,button:0,down:true},{$:'Move',x:10,y:10}]),true,640,640,{fst:setup,snd:a});
const direct=App.pick(b,setup,.5,.5,false);
assert.deepEqual(clicked.snd.landscape.world.cells,direct.landscape.world.cells);
assert.ok(clicked.snd.landscape.dirty!==0);
let repeated=Input.key(113,true,Input.initial(false));
repeated=Input.key(113,true,repeated);assert.equal(repeated.quality,2,'key repeat does not toggle resolution again');
repeated=Input.key(113,false,repeated);repeated=Input.key(113,true,repeated);assert.equal(repeated.quality,1);
const drag=Input.dragging(Input.initial(true),true,.5,.5);
const updated=Input.pointer(drag,.65,.55);
const simultaneous=App.mouse(true,true,0,.65,.55,drag,App.create(true));
const expectedEdit=App.pick(App.create(true),updated,.65,.55,false);
const canonical=value=>JSON.parse(JSON.stringify(value,(key,v)=>key==='$'?v.split('.').pop():v));
assert.deepEqual(canonical(simultaneous.fst),canonical(updated),'the button event updates the active drag pose');
assert.deepEqual(simultaneous.snd.landscape.world.cells,expectedEdit.landscape.world.cells,'picking uses the same updated camera pose');
console.log('PASS: chunk boundary rebuilding/cache reuse, input ordering, projection/resolution controls and camera motion while paused.');
