import assert from 'node:assert/strict';
import T from './cloth-input.bend';
import W from '../demos/cloth/world.bend';
import V from '../demos/cloth/view.bend';
import App from '../demos/cloth/main.bend';
const v=V.project(W.rest(32,528));
const down={$:'Mouse',x:Math.round(v.x*2),y:Math.round(v.y*2),button:0,down:true};
const moved={$:'Move',x:20,y:20};
const list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'});
assert.equal(T.batch(list([down,moved])),528,'pick at the press before a same-frame move leaves the surface');
assert.equal(T.batch(list([down,moved,{...down,down:false}])),0xffffffff,'release clears the grab');
console.log('PASS: press/move batching selects the pressed vertex and release clears selection.');
const controls={$:'Controls',gpu:false,paused:true,reset:false,quit:false,wind:true,hud:true,mx:200,my:230,picking:false,grab:528,grab_depth:7.2,scale_x:.5,scale_y:.5,high:false,aa:true,dof:true};
const quality=App.event({$:'Key',code:113,down:true},controls);
assert.deepEqual(quality,{...controls,high:true},'resolution preserves pause, grab, effects and does not request reset');
const f=T.fixture().value;
const state=f.state;
state.current.y[528]-=.12;state.previous.y[528]-=.08;
const saved=structuredClone(state);
const high=T.resize(true,f);
assert.equal(high.pixels.length,1048576);assert.equal(high.background.length,2097152);assert.equal(high.triangles.length,16384);
assert.deepEqual(high.state,saved,'higher resolution retains position, velocity and spatial state');
assert.equal(T.resize(true,high).pixels,high.pixels,'unchanged quality reuses buffers');
const low=T.resize(false,high);
assert.equal(low.pixels.length,262144);assert.equal(low.background.length,524288);assert.equal(low.triangles.length,2048);
assert.deepEqual(low.state,saved,'round-trip quality switch retains the deformed cloth');
assert.ok(App.label(quality,123,456).split('\n').every(line=>line.length<=16));
assert.ok(App.label(quality,123,456).split('\n').length<=16,'quality details fit the HUD');
console.log('PASS: resolution round trip preserves cloth deformation, velocity, grab and pause; same-resolution frames reuse buffers.');
