import assert from 'node:assert/strict';
import P from '../engine/render/post.bend';
const settings=(aa,dof,focus=10,aperture=6)=>({$:'Settings',aa,dof,focus,aperture});
assert.equal(P.radius(settings(true,true),10),0);
assert.equal(P.radius(settings(true,true),20),3);
assert.equal(P.radius(settings(true,true),1),3);
assert.equal(P.radius(settings(true,false),20),0);
assert.equal(P.address(8,0,-3,-3),64);
assert.equal(P.address(8,63,3,3),127);
assert.equal(P.edge_color(0xffffff,0,0xffffff,0xffffff,0xffffff),0xdfdfdf);
assert.equal(P.edge_color(0x606060,0x616161,0x606060,0x616161,0x606060),0x606060);
const source=Array.from({length:128},(_,i)=>({$:'Fragment',depth:10,color:i<64?0x123456:0xff0000}));
source[64+2+2*8]={$:'Fragment',depth:2,color:0xffffff};
const saved=structuredClone(source);
const r=P.gather(8,9n,3+3*8,1,10,{fst:source,snd:{$:'Sum',r:0,g:0,b:0,weight:0}});
assert.equal(r.snd.weight,8,'reject a foreground sample across the depth discontinuity');
assert.equal(P.resolved(0,r.snd),0xff0000,'foreground white cannot bleed into far red');
assert.deepEqual(r.fst,saved,'postprocess never changes source color/depth');
console.log('PASS: focus/CoC bounds, edge-only smoothing, finite image addressing and depth-aware gather.');
