import assert from 'node:assert/strict';
import fs from 'node:fs';
import P from '../../demos/turn/play.bend';
import F from '../../demos/turn/physics.bend';
import L from '../../demos/turn/levels.bend';
import {macro} from './controller.js';
const plans=JSON.parse(fs.readFileSync('tests/turn/projected-plans.json'));
const press=(p,c)=>P.key(c,false,P.key(c,true,p));
const reports=[];
let source='import Base\nimport ./model.bend as M\n\n# Generated by tests/turn/hint-routes.js from successful keyboard replays.\n# Exact pre-R positions, in world units (1024 per cube). Not cell approximations.\ntype Spot is Data:\n  Spot{plane: M.Plane, position: M.Point, order: U32, airborne: Bool}\n';
for(let level=0;level<L.count();level++){
 let p=P.create(level);const spots=[];
 for(const action of plans[level]){
  if(P.arrived(p))break;
  const run=macro(p,action);assert.ok(run);
  for(const t of run.trace){
   for(const [bit,code] of [[1,97],[2,100],[8,115]])p=P.key(code,!!(t.keys&bit),p);
   if(t.jump)p=press(p,32);
   if(t.turn){
    assert.ok(P.can_turn(p));assert.equal(p.turn,0);assert.equal(P.arrived(p),false);
    spots.push({plane:p.plane.$.split('.').at(-1),position:p.body.position,order:spots.length+1,airborne:!F.ground(level,p.plane,p.body.position)});
    p=press(p,114);
   }
   p=P.step(p);
  }
  assert.deepEqual(p,run.p);
 }
 assert.ok(P.arrived(p));assert.equal(p.seals,L.all_seals(level));assert.equal(spots.length,p.turns);
 const text=spots.map(s=>`Spot{M.${s.plane}{},M.Point{${s.position.x},${s.position.y},${s.position.z}},${s.order},${s.airborne?'True':'False'}{}}`).join(',');
 source+=`def level${level}() -> List<Spot>: [${text}]\n`;
 reports.push({level,spots,ending:{position:p.body.position,plane:p.plane.$.split(".").at(-1),turns:p.turns}});
}
source+='def route(level: U32) -> List<Spot>:\n  match level:\n'+reports.map(r=>`    case ${r.level}: level${r.level}()\n`).join('')+'    case _: []\n';
source+='type End is Data:\n  End{position: M.Point, plane: M.Plane, turns: U32}\n';
source+='def ending(level: U32) -> End:\n  match level:\n'+reports.map(({level,ending:e})=>`    case ${level}: End{M.Point{${e.position.x},${e.position.y},${e.position.z}},M.${e.plane}{},${e.turns}}\n`).join('')+'    case _: End{M.Point{9728,9728,512},M.XY{},0}\n';
if(process.argv.includes('--write'))fs.writeFileSync('demos/turn/hint-routes.bend',source);
else assert.equal(fs.readFileSync('demos/turn/hint-routes.bend','utf8'),source,'hint markers agree with successful keyboard replays');
fs.writeFileSync('build/turn-hint-routes.json',JSON.stringify(reports,null,2)+'\n');
console.log(`Validated ${reports.reduce((n,r)=>n+r.spots.length,0)} legal rotation hints in ${reports.length} winning routes.`);
