#!/usr/bin/env python3
"""Compile the hand-authored campaign catalog into pure Bend definitions."""
import json
import sys
from pathlib import Path
root = Path(__file__).resolve().parents[1]
def output(relative, content):
    file = root / relative
    if '--check' in sys.argv:
        if not file.exists() or file.read_text() != content:
            raise SystemExit(f'{relative} is stale; run scripts/generate-turn-levels.py')
    else:
        file.write_text(content)
catalog = json.loads((root / 'demos/turn/catalog.json').read_text())
levels, order = catalog['levels'], catalog['order']
assert [r['id'] for r in levels] == list(range(len(levels)))
assert sorted(order) == list(range(len(levels)))
assert len(levels) <= 32, 'completion marks use one U32'
assert all(isinstance(r['title'],str) and isinstance(r['hint'],str) for r in levels)
bool_bend = lambda v: 'True{}' if v else 'False{}'
def dispatch(name, argument, result, values, fallback):
    return f'def {name}({argument}: U32) -> {result}:\n  match {argument}:\n' + ''.join(f'    case {i}: {v}\n' for i,v in enumerate(values)) + f'    case _: {fallback}\n'
source = 'import Base\nimport ./model.bend as M\nimport ./terrain.bend as T\n\n# Generated by scripts/generate-turn-levels.py from catalog.json.\n'
source += f'def count() -> U32: {len(levels)}\n'
source += dispatch('at','chapter','U32',order,order[0])
source += dispatch('index','level','U32',[order.index(i) for i in range(len(levels))],0)
source += 'def next(level: U32) -> U32: at(((index(level) + 1) % count() : U32))\n'
source += 'def last(level: U32) -> Bool: U32.is_eq(index(level),(count() - 1 : U32))\n'
for field, result in [('title','String'),('hint','String'),('difficulty','U32'),('par','U32')]:
    values=[json.dumps(r[field]) if result=='String' else r[field] for r in levels]
    source += dispatch(field,'level',result,values,values[0])
source += dispatch('difficulty_name','difficulty','String',['""','"GENTLE"','"CURIOUS"','"TRICKY"','"EXPERT"','"MASTER"'],'"MASTER"')
source += dispatch('seal_count','level','U32',[len(r['seals']) for r in levels],0)
source += 'def flag(i: U32) -> U32: U32.shln(1,U32.to_nat(i))\n'
source += 'def all_seals(level: U32) -> U32: (U32.shln(1,U32.to_nat(seal_count(level))) - 1 : U32)\n'
source += 'def seal_total(+mask: U32) -> U32: (U32.and(mask,1) + U32.and(U32.shrn(mask,1n),1) + U32.and(U32.shrn(mask,2n),1) : U32)\n'
for r in levels:
    assert len(r['seals']) <= 3
    source += dispatch('seals'+str(r['id']),'i','M.Point', [f'M.Point{{{x},{y},{z}}}' for x,y,z in r['seals']], 'M.Point{99,99,99}')
source += 'def seal(level: U32, i: U32) -> M.Point:\n  match level:\n' + ''.join(f'    case {r["id"]}: seals{r["id"]}(i)\n' for r in levels) + '    case _: M.Point{99,99,99}\n'
source += dispatch('ring_count','level','U32',[len(r.get('rings',[])) for r in levels],0)
for r in levels:
    if r.get('rings'):
        source += dispatch('rings'+str(r['id']),'i','M.Point',[f'M.Point{{{x},{y},{z}}}' for x,y,z in r['rings']],'M.Point{99,99,99}')
source += 'def ring(level: U32, i: U32) -> M.Point:\n  match level:\n' + ''.join(f'    case {r["id"]}: rings{r["id"]}(i)\n' for r in levels if r.get('rings')) + '    case _: M.Point{99,99,99}\n'
source += 'def same_projection(a: M.Point, b: M.Point) -> Bool:\n  M.Point{x,y,_} = a\n  M.Point{u,v,_} = b\n  U32.is_eq(x,u) && U32.is_eq(y,v)\n'
source += 'def at_ring(+n: Nat, +level: U32, +p: M.Plane, +q: M.Point) -> Bool:\n  match n:\n    case 0n: False{}\n    case 1n+k: same_projection(M.local(p,q),M.local(p,ring(level,U32.from_nat(k)))) || at_ring(k,level,p,q)\n'
source += 'def turn_allowed(+level: U32, p: M.Plane, q: M.Point) -> Bool:\n  U32.is_eq(ring_count(level),0) || at_ring(U32.to_nat(ring_count(level)),level,p,q)\n'
for r in levels:
    if r['kind'] in ('room','projection'):
        assert len(set(map(tuple,r['blocks'])))==len(r['blocks'])
        assert all(0<=v<10 for q in r['blocks']+r.get('rings',[]) for v in q)
        source += f'def room_cells{r["id"]}(cell: U32) -> Bool:\n  match cell:\n'
        source += ''.join(f'    case {x+y*10+z*100}: True{{}}\n' for x,y,z in r['blocks'])+'    case _: False{}\n'
        source += f'def room{r["id"]}(+q: M.Point) -> Bool:\n  M.Point{{x,y,z}} = q\n  M.inside(q) && room_cells{r["id"]}((x + y * 10 + z * 100 : U32))\n'
source += 'def solid(level: U32, q: M.Point) -> Bool:\n  match level:\n'
for r in levels:
    k=r['kind']
    if k.startswith('classic'): call=['T.first(q)','T.second(q)','T.third(q)'][int(k[-1])]
    elif k=='paper': call='T.paper(q)'
    elif k=='fold': call='T.one_turn(q)'
    elif k=='switch': call=f'T.switchback({r["a"]},q)'
    elif k=='chain': call=f'T.chain({r["a"]},{r["b"]},{r.get("gaps",0)},{bool_bend(r.get("ridge",False))},{bool_bend(r.get("canopy",False))},q)'
    elif k in ('room','projection'): call=f'room{r["id"]}(q)'
    else: raise ValueError(k)
    source+=f'    case {r["id"]}: {call}\n'
source += '    case _: T.paper(q)\ndef free(level: U32, +q: M.Point) -> Bool:\n  M.inside(q) && Bool.not(solid(level,q))\n'
# Three immutable silhouettes of the same cubes. Precomputed ten-bit rows
# keep collision queries independent of depth and out of voxel search loops.
for r in levels:
    for plane,(a,b) in enumerate(((0,1),(1,2),(2,0))):
        rows=[sum(1<<x for x in {q[a] for q in r['blocks'] if q[b]==y}) for y in range(10)]
        assert any(row != 1023 for row in rows), 'every projection needs air for settling'
        source += dispatch(f'projection{r["id"]}_{plane}','y','U32',rows,1023)
    source += f'def projection{r["id"]}(p: M.Plane, y: U32) -> U32:\n  match p:\n'
    for plane,name in enumerate(('XY','YZ','ZX')):
        source += f'    case M.{name}{{}}: projection{r["id"]}_{plane}(y)\n'
# Cell-space escape certificates use the same downward-first / nearest-air
# rule as the continuous resolver. Explicit destinations keep reduction of
# exhaustive level laws bounded; tests compare them to the live resolver.
for r in levels:
    for plane,(a,b) in enumerate(((0,1),(1,2),(2,0))):
        occupied={(q[a],q[b]) for q in r['blocks']}
        air={(x,y) for x in range(10) for y in range(10)}-occupied
        assert air
        source += f'def escape{r["id"]}_{plane}(cell: U32) -> U32:\n  match cell:\n'
        for x,y in sorted(occupied,key=lambda q:q[0]+q[1]*10):
            below=[v for v in range(y) if (x,v) in air]
            target=(x,max(below)) if below else min(air,key=lambda q:(abs(q[0]-x)+abs(q[1]-y),-q[1],-q[0]))
            source += f'    case {x+y*10}: {target[0]+target[1]*10}\n'
        # Free cells bypass this table. Keep invalid input visibly out of bounds.
        source += '    case _: 100\n'
    source += f'def escape{r["id"]}(p: M.Plane, cell: U32) -> U32:\n  match p:\n'
    for plane,name in enumerate(('XY','YZ','ZX')):
        source += f'    case M.{name}{{}}: escape{r["id"]}_{plane}(cell)\n'
source += 'def escape_cell(level: U32, p: M.Plane, cell: U32) -> U32:\n  match level:\n'
source += ''.join(f'    case {r["id"]}: escape{r["id"]}(p,cell)\n' for r in levels)
source += '    case _: 100\n'
source += 'def projected_row(level: U32, p: M.Plane, y: U32) -> U32:\n  match level:\n'
source += ''.join(f'    case {r["id"]}: projection{r["id"]}(p,y)\n' for r in levels)
source += '    case _: 1023\n'
source += 'def projected_inside(inside: Bool, level: U32, p: M.Plane, x: U32, y: U32) -> Bool:\n  match inside:\n    case False{}: False{}\n    case True{}: U32.is_eq(U32.and(projected_row(level,p,y),U32.shln(1,U32.to_nat(x))),0)\n'
source += 'def projected_local(level: U32, p: M.Plane, q: M.Point) -> Bool:\n  M.Point{+x,+y,_} = q\n  projected_inside((x < 10 : U32) && (y < 10 : U32),level,p,x,y)\n'
source += 'def projected_free(level: U32, +p: M.Plane, q: M.Point) -> Bool:\n  projected_local(level,p,M.local(p,q))\n'
output('demos/turn/levels.bend',source)

# Each chapter has a separately checked constructive reachability witness.
laws='import Base\nimport ./model.bend as M\nimport ./rules.bend as R\nimport ./resolution-check.bend as Check\n\n'
proof='import Base\nimport ./CAMPAIGN_LAWS.bend as C\nimport ./solutions.bend as S\n\n'
for row in levels:
    i=row['id']
    laws+=f'law level{i}_possible:\n  exs path: List<R.Beat>\n  {{R.certified({i},path,M.origin()) == True{{}} : Bool}}\n'
    proof+=f'def C.level{i}_possible(): (S.path{i}(),{{==}})\n'
    laws+=f'law level{i}_settling_total:\n  {{Check.level({i}) == True{{}} : Bool}}\n'
    proof+=f'def C.level{i}_settling_total(): {{==}}\n'
output('demos/turn/CAMPAIGN_LAWS.bend',laws)
output('demos/turn/CAMPAIGN_PROOF.bend',proof)
